### PR TITLE
Change FactorAPI to interface

### PR DESCRIPTION
**Pull request by loganullmeyer**

### CODE REVIEW

**Comment by loganullmeyer** [comment]
This all compiles fine on my laptop, not sure why it isn't compiling here. I'll take another look tomorrow

**Comment by Oliver-222** [comment]
Copied Error Results:

> Task :compileJava FAILED
/home/runner/work/Software-Engineering-Project/Software-Engineering-Project/src/FactorAPI/FactorAPIImpl.java:21: error: incompatible types: ArrayList<Integer> cannot be converted to InputConfig
		ComputeRequest computeRequest = new ComputeRequest((ArrayList<Integer>) readResponse.getData(), factorRequest.getSource(), factorRequest.getDestination());
		                                                   ^
/home/runner/work/Software-Engineering-Project/Software-Engineering-Project/src/FactorAPI/FactorAPIImpl.java:22: error: constructor ComputeEngineImpl in class ComputeEngineImpl cannot be applied to given types;
		ComputeEngine computeEngine = new ComputeEngineImpl(computeRequest);
		                              ^
  required: no arguments
  found:    ComputeRequest
  reason: actual and formal argument lists differ in length

**Comment by loganullmeyer** [comment]
This got really convoluted because this branch is a bunch of commits behind main. It'll take a minute to fix and update everything

**Comment by loganullmeyer** [comment]
I genuinely think it'll be easier to just close this and open a new pr from main

**Pull request closed without merging**
